### ISSUE TITLE
Joining catalog fields reports error

### ISSUE THREAD

**Issue by daniel-berger-nemeth** [alnv/catalog-manager#303] opened 2021-04-07 12:20 UTC
Hi. 
I have two select fields called driver and creator. Both are loading the values from tl_member. When I create now a frontend module and want to join both catalog fields to get firstname and lastname, I get an error.

Seems the problem is, because the field gets the name tl_memberFirstname and tl_memberLastname for both.

Cheers

**Comment by daniel-berger-nemeth** [comment] 2021-04-09 07:45
Here is the error from log:
`[2021-04-09 09:44:12] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing 'SELECT dps_car_reservation.*,tl_member.`id` AS tl_memberId,tl_member.`tstamp` AS tl_memberTstamp,tl_member.`firstname` AS tl_memberFirstname,tl_member.`lastname` AS tl_memberLastname,tl_member.`dateOfBirth` AS tl_memberDateOfBirth,tl_member.`gender` AS tl_memberGender,tl_member.`company` AS tl_memberCompany,tl_member.`street` AS tl_memberStreet,tl_member.`postal` AS tl_memberPostal,tl_member.`city` AS tl_memberCity,tl_member.`state` AS tl_memberState,tl_member.`country` AS tl_memberCountry,tl_member.`phone` AS tl_memberPhone,tl_member.`mobile` AS tl_memberMobile,tl_member.`fax` AS tl_memberFax,tl_member.`email` AS tl_memberEmail,tl_member.`website` AS tl_memberWebsite,tl_member.`language` AS tl_memberLanguage,tl_member.`groups` AS tl_memberGroups,tl_member.`login` AS tl_memberLogin,tl_member.`username` AS tl_memberUsername,tl_member.`password` AS tl_memberPassword,tl_member.`assignDir` AS tl_memberAssignDir,tl_member.`homeDir` AS tl_memberHomeDir,tl_member.`disable` AS tl_memberDisable,tl_member.`start` AS tl_memberStart,tl_member.`stop` AS tl_memberStop,tl_member.`dateAdded` AS tl_memberDateAdded,tl_member.`lastLogin` AS tl_memberLastLogin,tl_member.`currentLogin` AS tl_memberCurrentLogin,tl_member.`loginAttempts` AS tl_memberLoginAttempts,tl_member.`locked` AS tl_memberLocked,tl_member.`session` AS tl_memberSession,tl_member.`secret` AS tl_memberSecret,tl_member.`useTwoFactor` AS tl_memberUseTwoFactor,tl_member.`backupCodes` AS tl_memberBackupCodes,tl_member.`trustedTokenVersion` AS tl_memberTrustedTokenVersion,tl_member.`dps_rank` AS tl_memberDps_rank,tl_member.`dps_registry_no` AS tl_memberDps_registry_no,tl_member.`dps_cabinet_no` AS tl_memberDps_cabinet_no,tl_member.`dps_cabinet_alarm_no` AS tl_memberDps_cabinet_alarm_no,tl_member.`dps_squad` AS tl_memberDps_squad,tl_member.`dps_group` AS tl_memberDps_group,tl_member.`dps_gab` AS tl_memberDps_gab,tl_member.`dps_grazmodul` AS tl_memberDps_grazmodul,tl_member.`dps_agt` AS tl_memberDps_agt,tl_member.`dps_kdt_gruppe` AS tl_memberDps_kdt_gruppe,tl_member.`dps_kdt_trupp` AS tl_memberDps_kdt_trupp,tl_member.`dps_kdt_bsw` AS tl_memberDps_kdt_bsw,tl_member.`dps_ma_smaller_75` AS tl_memberDps_ma_smaller_75,tl_member.`dps_ma_bigger_75` AS tl_memberDps_ma_bigger_75,tl_member.`dps_ma_special` AS tl_memberDps_ma_special,tl_member.`notice` AS tl_memberNotice,tl_member.`dps_eh` AS tl_memberDps_eh,tl_member.`dps_admin` AS tl_memberDps_admin,tl_member.`dps_rank_date` AS tl_memberDps_rank_date,tl_member.`dps_emergency_type` AS tl_memberDps_emergency_type,tl_member.`dps_emergency_name` AS tl_memberDps_emergency_name,tl_member.`dps_emergency_number` AS tl_memberDps_emergency_number,tl_member.`dps_emergency_email` AS tl_memberDps_emergency_email,tl_member.`id` AS tl_memberId,tl_member.`tstamp` AS tl_memberTstamp,tl_member.`firstname` AS tl_memberFirstname,tl_member.`lastname` AS tl_memberLastname,tl_member.`dateOfBirth` AS tl_memberDateOfBirth,tl_member.`gender` AS tl_memberGender,tl_member.`company` AS tl_memberCompany,tl_member.`street` AS tl_memberStreet,tl_member.`postal` AS tl_memberPostal,tl_member.`city` AS tl_memberCity,tl_member.`state` AS tl_memberState,tl_member.`country` AS tl_memberCountry,tl_member.`phone` AS tl_memberPhone,tl_member.`mobile` AS tl_memberMobile,tl_member.`fax` AS tl_memberFax,tl_member.`email` AS tl_memberEmail,tl_member.`website` AS tl_memberWebsite,tl_member.`language` AS tl_memberLanguage,tl_member.`groups` AS tl_memberGroups,tl_member.`login` AS tl_memberLogin,tl_member.`username` AS tl_memberUsername,tl_member.`password` AS tl_memberPassword,tl_member.`assignDir` AS tl_memberAssignDir,tl_member.`homeDir` AS tl_memberHomeDir,tl_member.`disable` AS tl_memberDisable,tl_member.`start` AS tl_memberStart,tl_member.`stop` AS tl_memberStop,tl_member.`dateAdded` AS tl_memberDateAdded,tl_member.`lastLogin` AS tl_memberLastLogin,tl_member.`currentLogin` AS tl_memberCurrentLogin,tl_member.`loginAttempts` AS tl_memberLoginAttempts,tl_member.`locked` AS tl_memberLocked,tl_member.`session` AS tl_memberSession,tl_member.`secret` AS tl_memberSecret,tl_member.`useTwoFactor` AS tl_memberUseTwoFactor,tl_member.`backupCodes` AS tl_memberBackupCodes,tl_member.`trustedTokenVersion` AS tl_memberTrustedTokenVersion,tl_member.`dps_rank` AS tl_memberDps_rank,tl_member.`dps_registry_no` AS tl_memberDps_registry_no,tl_member.`dps_cabinet_no` AS tl_memberDps_cabinet_no,tl_member.`dps_cabinet_alarm_no` AS tl_memberDps_cabinet_alarm_no,tl_member.`dps_squad` AS tl_memberDps_squad,tl_member.`dps_group` AS tl_memberDps_group,tl_member.`dps_gab` AS tl_memberDps_gab,tl_member.`dps_grazmodul` AS tl_memberDps_grazmodul,tl_member.`dps_agt` AS tl_memberDps_agt,tl_member.`dps_kdt_gruppe` AS tl_memberDps_kdt_gruppe,tl_member.`dps_kdt_trupp` AS tl_memberDps_kdt_trupp,tl_member.`dps_kdt_bsw` AS tl_memberDps_kdt_bsw,tl_member.`dps_ma_smaller_75` AS tl_memberDps_ma_smaller_75,tl_member.`dps_ma_bigger_75` AS tl_memberDps_ma_bigger_75,tl_member.`dps_ma_special` AS tl_memberDps_ma_special,tl_member.`notice` AS tl_memberNotice,tl_member.`dps_eh` AS tl_memberDps_eh,tl_member.`dps_admin` AS tl_memberDps_admin,tl_member.`dps_rank_date` AS tl_memberDps_rank_date,tl_member.`dps_emergency_type` AS tl_memberDps_emergency_type,tl_member.`dps_emergency_name` AS tl_memberDps_emergency_name,tl_member.`dps_emergency_number` AS tl_memberDps_emergency_number,tl_member.`dps_emergency_email` AS tl_memberDps_emergency_email FROM dps_car_reservation JOIN tl_member ON dps_car_reservation.`request_by` = tl_member.`id`  JOIN tl_member ON dps_car_reservation.`driver` = tl_member.`id` WHERE LOWER(CAST(dps_car_reservation.`date_start` AS SIGNED)) > 1617919200 ORDER BY dps_car_reservation.`date_start` ASC':  SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 'tl_member'" at /var/www/vhosts/ff-graz.at/dienstplan.ff-graz.at/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 110 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'SELECT dps_car_reservation.*,tl_member.`id` AS tl_memberId,tl_member.`tstamp` AS tl_memberTstamp,tl_member.`firstname` AS tl_memberFirstname,tl_member.`lastname` AS tl_memberLastname,tl_member.`dateOfBirth` AS tl_memberDateOfBirth,tl_member.`gender` AS tl_memberGender,tl_member.`company` AS tl_memberCompany,tl_member.`street` AS tl_memberStreet,tl_member.`postal` AS tl_memberPostal,tl_member.`city` AS tl_memberCity,tl_member.`state` AS tl_memberState,tl_member.`country` AS tl_memberCountry,tl_member.`phone` AS tl_memberPhone,tl_member.`mobile` AS tl_memberMobile,tl_member.`fax` AS tl_memberFax,tl_member.`email` AS tl_memberEmail,tl_member.`website` AS tl_memberWebsite,tl_member.`language` AS tl_memberLanguage,tl_member.`groups` AS tl_memberGroups,tl_member.`login` AS tl_memberLogin,tl_member.`username` AS tl_memberUsername,tl_member.`password` AS tl_memberPassword,tl_member.`assignDir` AS tl_memberAssignDir,tl_member.`homeDir` AS tl_memberHomeDir,tl_member.`disable` AS tl_memberDisable,tl_member.`start` AS tl_memberStart,tl_member.`stop` AS tl_memberStop,tl_member.`dateAdded` AS tl_memberDateAdded,tl_member.`lastLogin` AS tl_memberLastLogin,tl_member.`currentLogin` AS tl_memberCurrentLogin,tl_member.`loginAttempts` AS tl_memberLoginAttempts,tl_member.`locked` AS tl_memberLocked,tl_member.`session` AS tl_memberSession,tl_member.`secret` AS tl_memberSecret,tl_member.`useTwoFactor` AS tl_memberUseTwoFactor,tl_member.`backupCodes` AS tl_memberBackupCodes,tl_member.`trustedTokenVersion` AS tl_memberTrustedTokenVersion,tl_member.`dps_rank` AS tl_memberDps_rank,tl_member.`dps_registry_no` AS tl_memberDps_registry_no,tl_member.`dps_cabinet_no` AS tl_memberDps_cabinet_no,tl_member.`dps_cabinet_alarm_no` AS tl_memberDps_cabinet_alarm_no,tl_member.`dps_squad` AS tl_memberDps_squad,tl_member.`dps_group` AS tl_memberDps_group,tl_member.`dps_gab` AS tl_memberDps_gab,tl_member.`dps_grazmodul` AS tl_memberDps_grazmodul,tl_member.`dps_agt` AS tl_memberDps_agt,tl_member.`dps_kdt_gruppe` AS tl_memberDps_kdt_gruppe,tl_member.`dps_kdt_trupp` AS tl_memberDps_kdt_trupp,tl_member.`dps_kdt_bsw` AS tl_memberDps_kdt_bsw,tl_member.`dps_ma_smaller_75` AS tl_memberDps_ma_smaller_75,tl_member.`dps_ma_bigger_75` AS tl_memberDps_ma_bigger_75,tl_member.`dps_ma_special` AS tl_memberDps_ma_special,tl_member.`notice` AS tl_memberNotice,tl_member.`dps_eh` AS tl_memberDps_eh,tl_member.`dps_admin` AS tl_memberDps_admin,tl_member.`dps_rank_date` AS tl_memberDps_rank_date,tl_member.`dps_emergency_type` AS tl_memberDps_emergency_type,tl_member.`dps_emergency_name` AS tl_memberDps_emergency_name,tl_member.`dps_emergency_number` AS tl_memberDps_emergency_number,tl_member.`dps_emergency_email` AS tl_memberDps_emergency_email,tl_member.`id` AS tl_memberId,tl_member.`tstamp` AS tl_memberTstamp,tl_member.`firstname` AS tl_memberFirstname,tl_member.`lastname` AS tl_memberLastname,tl_member.`dateOfBirth` AS tl_memberDateOfBirth,tl_member.`gender` AS tl_memberGender,tl_member.`company` AS tl_memberCompany,tl_member.`street` AS tl_memberStreet,tl_member.`postal` AS tl_memberPostal,tl_member.`city` AS tl_memberCity,tl_member.`state` AS tl_memberState,tl_member.`country` AS tl_memberCountry,tl_member.`phone` AS tl_memberPhone,tl_member.`mobile` AS tl_memberMobile,tl_member.`fax` AS tl_memberFax,tl_member.`email` AS tl_memberEmail,tl_member.`website` AS tl_memberWebsite,tl_member.`language` AS tl_memberLanguage,tl_member.`groups` AS tl_memberGroups,tl_member.`login` AS tl_memberLogin,tl_member.`username` AS tl_memberUsername,tl_member.`password` AS tl_memberPassword,tl_member.`assignDir` AS tl_memberAssignDir,tl_member.`homeDir` AS tl_memberHomeDir,tl_member.`disable` AS tl_memberDisable,tl_member.`start` AS tl_memberStart,tl_member.`stop` AS tl_memberStop,tl_member.`dateAdded` AS tl_memberDateAdded,tl_member.`lastLogin` AS tl_memberLastLogin,tl_member.`currentLogin` AS tl_memberCurrentLogin,tl_member.`loginAttempts` AS tl_memberLoginAttempts,tl_member.`locked` AS tl_memberLocked,tl_member.`session` AS tl_memberSession,tl_member.`secret` AS tl_memberSecret,tl_member.`useTwoFactor` AS tl_memberUseTwoFactor,tl_member.`backupCodes` AS tl_memberBackupCodes,tl_member.`trustedTokenVersion` AS tl_memberTrustedTokenVersion,tl_member.`dps_rank` AS tl_memberDps_rank,tl_member.`dps_registry_no` AS tl_memberDps_registry_no,tl_member.`dps_cabinet_no` AS tl_memberDps_cabinet_no,tl_member.`dps_cabinet_alarm_no` AS tl_memberDps_cabinet_alarm_no,tl_member.`dps_squad` AS tl_memberDps_squad,tl_member.`dps_group` AS tl_memberDps_group,tl_member.`dps_gab` AS tl_memberDps_gab,tl_member.`dps_grazmodul` AS tl_memberDps_grazmodul,tl_member.`dps_agt` AS tl_memberDps_agt,tl_member.`dps_kdt_gruppe` AS tl_memberDps_kdt_gruppe,tl_member.`dps_kdt_trupp` AS tl_memberDps_kdt_trupp,tl_member.`dps_kdt_bsw` AS tl_memberDps_kdt_bsw,tl_member.`dps_ma_smaller_75` AS tl_memberDps_ma_smaller_75,tl_member.`dps_ma_bigger_75` AS tl_memberDps_ma_bigger_75,tl_member.`dps_ma_special` AS tl_memberDps_ma_special,tl_member.`notice` AS tl_memberNotice,tl_member.`dps_eh` AS tl_memberDps_eh,tl_member.`dps_admin` AS tl_memberDps_admin,tl_member.`dps_rank_date` AS tl_memberDps_rank_date,tl_member.`dps_emergency_type` AS tl_memberDps_emergency_type,tl_member.`dps_emergency_name` AS tl_memberDps_emergency_name,tl_member.`dps_emergency_number` AS tl_memberDps_emergency_number,tl_member.`dps_emergency_email` AS tl_memberDps_emergency_email FROM dps_car_reservation JOIN tl_member ON dps_car_reservation.`request_by` = tl_member.`id`  JOIN tl_member ON dps_car_reservation.`driver` = tl_member.`id` WHERE LOWER(CAST(dps_car_reservation.`date_start` AS SIGNED)) > 1617919200 ORDER BY dps_car_reservation.`date_start` ASC':\n\nSQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 'tl_member' at /var/www/vhosts/ff-graz.at/dienstplan.ff-graz.at/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:110, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 'tl_member' at /var/www/vhosts/ff-graz.at/dienstplan.ff-graz.at/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:91, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 'tl_member' at /var/www/vhosts/ff-graz.at/dienstplan.ff-graz.at/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:86)"} []`

**Comment by alnv** [comment] 2021-04-09 11:39
should fixed in v1.31.46

**Comment by daniel-berger-nemeth** [comment] 2021-04-09 11:41
Cheers

**Comment by daniel-berger-nemeth** [comment] 2021-04-09 14:42
Updated now to the version but the second joined table is not available in template vars. Only the first on. Seems they are overriding each other?

**Comment by alnv** [comment] 2021-04-09 17:48
Cannot reproduce it. Multiple joins should be numbered:
$this->tl_memberEmail
$this->tl_member2Email
$this->tl_member3Email

**Comment by RoToK4** [comment] 2021-04-13 06:08
That works great.
But now it is unfortunately the case that if one of the fields is empty, a 404 error occurs on the detail page.

**Comment by daniel-berger-nemeth** [comment] 2021-04-13 06:44
> That works great.
> 
> But now it is unfortunately the case that if one of the fields is empty, a 404 error occurs on the detail page.

For me it dont work together with the taxonomy. If i have taxonomy enabled and join two tl_member select fields, the output is zero

**Comment by alnv** [comment] 2021-04-13 15:30
You can change the join type in your localconfig.php:
$GLOBALS['TL_CONFIG']['catalogJoinType'] = 'LEFT JOIN';
OR
$GLOBALS['TL_CONFIG']['catalogJoinType'] = 'RIGHT JOIN';

Taxonomy and Joined Fields do not work together.

**Comment by RoToK4** [comment] 2021-04-14 06:11
> You can change the join type in your localconfig.php:
> $GLOBALS['TL_CONFIG']['catalogJoinType'] = 'LEFT JOIN';
> OR
> $GLOBALS['TL_CONFIG']['catalogJoinType'] = 'RIGHT JOIN';

That´s it! Thanks!

**Closed** 2021-05-06 18:41 UTC
Labels: bug
